[project]
name = "cs3264"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11, <=3.12"
dependencies = [
    "flask>=3.1.0",
    "groq>=0.20.0",
    "openai>=1.68.2",
    "pandas>=2.2.3",
    "python-dotenv>=1.0.1",
    "streamlit>=1.43.2",
]
